routes/web.php
<?php

use App\Http\Controllers\Dashboard\CompanyController;
use App\Http\Controllers\Dashboard\EmployeeController;
use App\Http\Controllers\ProfileController;
use App\Models\Employee;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Dashboard routes
Route::prefix('dashboard')->group(function () {

    // Dashboard homepage
    Route::get('/', function () {
        return view('dashboard.index');
    })->name('dashboard');

    // Dashboard category resource
    Route::resource('companies', CompanyController::class);

    // Dashboard tag resource
    Route::resource('employees', EmployeeController::class);
    Route::get('datatable-data', [CompanyController::class, 'getData'])->name('datatable.data');

})->middleware(['auth', 'verified']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

resources/views/dashboard/layouts/base/_navbar.blade.php
<!-- navbar-->
<header class="header">
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
                <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars">
                        </i></a><a href="{{route('dashboard')}}" class="navbar-brand">
                        <div class="brand-text d-none d-md-inline-block"><span>MINI </span><strong class="text-primary">
                                CRM</strong></div>
                    </a></div>
                <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                    <!-- Notifications dropdown-->
                    <li class="nav-item dropdown"> <a id="notifications" rel="nofollow" data-target="#" href="#"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i
                                class="fa fa-bell"></i><span class="badge badge-warning"
                                id="notifications-count"></span></a>
                        <ul aria-labelledby="notifications" class="dropdown-menu">
                            <li><a rel="nofollow" href="#" class="dropdown-item">
                                    <div class="notification d-flex justify-content-between">
                                        <div class="notification-content"><i class="fa fa-envelope"></i>You have 6 new
                                            messages </div>
                                        <div class="notification-time"><small>4 minutes ago</small></div>
                                    </div>
                                </a></li>
                            <li><a rel="nofollow" href="#" class="dropdown-item">
                                    <div class="notification d-flex justify-content-between">
                                        <div class="notification-content"><i class="fa fa-twitter"></i>You have 2
                                            followers</div>
                                        <div class="notification-time"><small>4 minutes ago</small></div>
                                    </div>
                                </a></li>
                            <li><a rel="nofollow" href="#" class="dropdown-item">
                                    <div class="notification d-flex justify-content-between">
                                        <div class="notification-content"><i class="fa fa-upload"></i>Server Rebooted
                                        </div>
                                        <div class="notification-time"><small>4 minutes ago</small></div>
                                    </div>
                                </a></li>
                            <li><a rel="nofollow" href="#" class="dropdown-item">
                                    <div class="notification d-flex justify-content-between">
                                        <div class="notification-content"><i class="fa fa-twitter"></i>You have 2
                                            followers</div>
                                        <div class="notification-time"><small>10 minutes ago</small></div>
                                    </div>
                                </a></li>
                            <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center">
                                    <strong> <i class="fa fa-bell"></i>view all notifications </strong></a></li>
                        </ul>
                    </li>
                    <!-- Messages dropdown-->
                    <li class="nav-item dropdown"> <a id="messages" rel="nofollow" data-target="#" href="#"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i
                                class="fa fa-envelope"></i><span class="badge badge-info">10</span></a>
                        <ul aria-labelledby="notifications" class="dropdown-menu">
                            <li><a rel="nofollow" href="#" class="dropdown-item d-flex">
                                    <div class="msg-profile"> <img src="/dashboard/img/avatar-1.jpg" alt="..."
                                            class="img-fluid rounded-circle"></div>
                                    <div class="msg-body">
                                        <h3 class="h5">Jason Doe</h3><span>sent you a direct message</span><small>3
                                            days ago at 7:58 pm - 10.06.2014</small>
                                    </div>
                                </a></li>
                            <li><a rel="nofollow" href="#" class="dropdown-item d-flex">
                                    <div class="msg-profile"> <img src="/dashboard/img/avatar-2.jpg" alt="..."
                                            class="img-fluid rounded-circle"></div>
                                    <div class="msg-body">
                                        <h3 class="h5">Frank Williams</h3><span>sent you a direct
                                            message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                                    </div>
                                </a></li>
                            <li><a rel="nofollow" href="#" class="dropdown-item d-flex">
                                    <div class="msg-profile"> <img src="/dashboard/img/avatar-3.jpg" alt="..."
                                            class="img-fluid rounded-circle"></div>
                                    <div class="msg-body">
                                        <h3 class="h5">Ashley Wood</h3><span>sent you a direct
                                            message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                                    </div>
                                </a></li>
                            <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center">
                                    <strong> <i class="fa fa-envelope"></i>Read all messages </strong></a></li>
                        </ul>
                    </li>
                    <!-- Log out-->
                    <li class="nav-item"><a href="{{route('logout')}}" class="nav-link logout"> <span
                                class="d-none d-sm-inline-block">Logout</span><i class="fa fa-sign-out"></i></a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

resources/views/dashboard/layouts/base/_sidebar.blade.php
<!-- Side Navbar -->
<nav class="side-navbar">
    <div class="side-navbar-wrapper">
        <!-- Sidebar Header    -->
        <div class="sidenav-header d-flex align-items-center justify-content-center">
            <!-- User Info-->
            <div class="sidenav-header-inner text-center">
                <h2 class="h5">{{ auth()->user()->name }}</h2><span>System Admin</span>
            </div>
            <!-- Small Brand information, appears on minimized sidebar-->
            <div class="sidenav-header-logo"><a href="/index.html" class="brand-small text-center">
                    <strong>B</strong><strong class="text-primary">D</strong></a></div>
        </div>
        <!-- Sidebar Navigation Menus-->
        <div class="main-menu">
            <h5 class="sidenav-heading">Main</h5>
            <ul id="side-main-menu" class="side-menu list-unstyled">
                <li><a href="#companiesdropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i
                            class="icon-user"></i>companies </a>
                    <ul id="companiesdropdownDropdown" class="collapse list-unstyled ">
                        <li><a href="{{ route('companies.create') }}">Add company</a></li>
                        <li><a href="{{ route('companies.index') }}">Show companies</a></li>
                    </ul>
                </li>
                <li><a href="#employeesdropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i
                            class="icon-padnote"></i>{{ __('Employees') }}</a>
                    <ul id="employeesdropdownDropdown" class="collapse list-unstyled ">
                        <li><a href="{{ route('employees.create') }}">Add Employee</a></li>
                        <li><a href="{{ route('employees.index') }}">Show Employees</a></li>
                    </ul>
                </li>

            </ul>
        </div>

    </div>
</nav>