routes/web.php
<?php

use App\Http\Controllers\Dashboard\CompanyController;
use App\Http\Controllers\Dashboard\EmployeeController;
use App\Http\Controllers\ProfileController;
use App\Models\Employee;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Dashboard routes
Route::prefix('dashboard')->group(function () {

    // Dashboard homepage
    Route::get('/', function () {
        return view('dashboard.index');
    })->name('dashboard');

    // Dashboard category resource
    Route::resource('companies', CompanyController::class);

    // Dashboard tag resource
    Route::resource('employees', EmployeeController::class);
    Route::get('datatable-data', [CompanyController::class, 'getData'])->name('datatable.data');

})->middleware(['auth', 'verified']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Company extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'logo',
        'website_url',
    ];

    public function employees(): HasMany
    {
        return $this->hasMany(Employee::class);
    }

    public function getLogoUrlAttribute()
    {
        if (Str::contains($this->logo, 'http')) {
            return $this->logo;
        }

        return str_replace('\\', '/', Storage::disk('public')->url($this->logo));
    }
}

app/Http/Controllers/Api/CompanyController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Employee;
use App\Traits\Responsable;

class CompanyController extends Controller
{
    use Responsable;

    public function getAllAvilableEmployeesByCompanyId(string $id)
    {
        $employees = Employee::query()
                        ->where('company_id', '=', $id)->get();

        return $this->success(
            'get All Avilable Employees in company ID '.$id,
            [
                'employees'=>$employees
            ]
        );
    }

    public function getNumberOfInternedEmployees()
    {
        $internedEmployeesCount = Employee::query()
                                  ->where('is_intern', '=', true)->count();
        return $this->success(
                'get Number Of Interned Employees',
                [
                 'interned_employees_count'=>$internedEmployeesCount
                ]
            );
    }
}

app/Http/Controllers/Dashboard/CompanyController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Company\CreateCompanyRequest;
use App\Http\Requests\Dashboard\Company\UpdateCompanyRequest;
use App\Mail\NewCompanyMail;
use App\Models\Company;
use App\Traits\UploadMedia;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class CompanyController extends Controller
{
    use UploadMedia;

    public function index(Request $request): View
    {
        $search = $request->input('search');
        $companiesQuery = Company::query();
        if ($search) {
            $companiesQuery->where('name', 'like', '%'.$search.'%')
                ->orWhere('email', 'like', '%'.$search.'%');
        }
        $companies = $companiesQuery->paginate(10);

        return view('dashboard.companies.index',
            ['companies' => $companies]
        );
    }

    public function create(): View
    {
        return view('dashboard.companies.create');
    }

    public function store(CreateCompanyRequest $request): RedirectResponse
    {
        $company = new company();
        $company->name = $request->validated('name');
        $company->email = $request->validated('email');
        $company->logo = $this->uploadImage('logo', 'company');
        $company->website_url = $request->validated('website_url');
        $company->save();
        Mail::to($company)->send(new NewCompanyMail($company));

        return redirect()->route('companies.index');
    }

    public function show(string $id): View
    {
        $company = Company::with('employees')->find($id);

        return view('dashboard.companies.show',
            ['company' => $company]
        );
    }

    public function edit(Company $company): View
    {
        return view('dashboard.companies.edit',
            ['company' => $company]
        );
    }

    public function update(UpdateCompanyRequest $request, Company $company): RedirectResponse
    {
        $company->name = $request->validated('name');
        $company->email = $request->validated('email');

        if ($request->hasfile('logo')) {
            $company->logo = $this->uploadImage('logo', 'company');
        }
        $company->website_url = $request->validated('website_url');
        $company->save();

        return redirect()->route('companies.index');
    }

    public function destroy(Company $company): RedirectResponse
    {
        $company->delete();

        return redirect()->route('companies.index');
    }
}

app/Http/Controllers/Dashboard/EmployeeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Employee\CreateEmployeeRequest;
use App\Http\Requests\Dashboard\Employee\UpdateEmployeeRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request): View
    {
        $search = $request->input('search');

        // Query to fetch employees
        $employeesQuery = Employee::query();

        // Apply search filter if search term is provided
        if ($search) {
            $employeesQuery->where('first_name', 'like', '%' . $search . '%')
                           ->orWhere('last_name', 'like', '%' . $search . '%')
                           ->orWhere('email', 'like', '%' . $search . '%');
        }
        $employees = $employeesQuery->paginate(10); // You can change the pagination limit as needed
        return view('dashboard.employees.index', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $companies = Company::all();

        return view('dashboard.employees.create', ['companies' => $companies]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateEmployeeRequest $request): RedirectResponse
    {
        $employee = new Employee();
        $employee->company_id = $request->validated('company_id');
        $employee->first_name = $request->validated('first_name');
        $employee->last_name = $request->validated('last_name');
        $employee->email = $request->validated('email');
        $employee->phone_number = $request->validated('phone_number');
        $employee->save();

        return redirect()->route('employees.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id): view
    {
        $employee = Employee::find($id);

        return view('dashboard.employees.show', ['employee' => $employee]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Employee $employee): view
    {
        $companies = Company::all();
        return view('dashboard.employees.edit',
            [
                'companies' => $companies,
                'employee' => $employee,
            ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee): RedirectResponse
    {
        $employee->company_id = $request->validated('company_id');
        $employee->first_name = $request->validated('first_name');
        $employee->last_name = $request->validated('last_name');
        $employee->email = $request->validated('email');
        $employee->phone_number = $request->validated('phone_number');
        $employee->save();

        return redirect()->route('employees.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id): RedirectResponse
    {
        $employee = Employee::find($id);
        $employee->delete();

        return redirect()->route('employees.index');
    }
}

resources/views/dashboard/companies/create.blade.php
@extends('dashboard.index')
@section('content')
    <div class="container px-5 mt-4">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="card">
            <div class="card-header d-flex">
                <h3 class="text-xl text-gray font-weight-bold">Add new Company</h3>
            </div>
            <div class="card-body">
                <form action="{{route('companies.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" placeholder="name" class="form-control" name="name">
                    </div>
                    <div class="form-group mt-2">
                        <label>Email</label>
                        <input type="email" placeholder="email" class="form-control " name="email">
                    </div>
                    <div class="form-group mt-2">
                        <label>Link</label>
                        <input type="link" placeholder="website url" class="form-control" name="website_url">
                    </div>

                    <div class="form-group ">
                        <label>Logo</label>
                        <input type="file" placeholder="Logo" class="form-control" name="logo">
                    </div>

                    <div class="form-group mt-2">
                        <input type="submit" value="Add Company" class="btn btn-primary my-4 rounded">
                    </div>
                </form>
            </div>
        </div>
    </div>


    @endsection

resources/views/dashboard/companies/edit.blade.php
@extends('dashboard.index')
@section('content')
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Update current Company</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('companies.update', $company->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" placeholder="name" class="form-control" name="name"
                            value="{{ $company->name ? $company->name : '' }}">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" placeholder="Email Address" class="form-control" name="email"
                            value="{{ $company->email ? $company->email : '' }}">
                    </div>
                    <div class="form-group">
                        <label>Website url</label>
                        <input type="text" placeholder="Website url" class="form-control" name="website_url"
                            value="{{ $company->website_url ? $company->website_url : '' }}">
                    </div>
                    <div class="form-group">
                        <label>Logo</label>
                        <input type="file" placeholder="Logo" class="form-control" name="logo">
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update Company" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/companies/index.blade.php
@extends('dashboard.index')
@section('content')
    <div class="container px-5 mt-4">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h3 class="text-xl text-gray font-weight-bold">Companies Info</h3>
                <form action="{{ route('companies.index') }}" method="GET" class="form-inline">
                    <input type="text" name="search" class="form-control mr-2" placeholder="Search...">
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>
            <div class="card-body">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>company name</th>
                                    <th>Email</th>
                                    <th class="text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($companies as $key => $company)
                                    <tr style="vertical-align: center">
                                        <td>{{ $company->id }}</td>
                                        <td>{{ $company->name }}</td>
                                        <td>{{ $company->email }}</td>

                                        <td class="d-flex justify-content-end">
                                            <a href="{{ route('companies.edit', $company->id) }}"> <button
                                                    class="btn btn-primary  rounded mr-1"
                                                    style="width: 4.5rem">Edit</button>
                                            </a>
                                            <a href="{{ route('companies.show', $company->id) }}"> <button
                                                    class="btn btn-info rounded px-2 mr-1"
                                                    style="width: 4.5rem">Show</button>
                                            </a>
                                            <form method="post"
                                                action="{{ route('companies.destroy', ['company' => $company->id]) }}"
                                                class="inline">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <button class="btn btn-danger rounded"style="width: 4.5rem">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $companies->links() }}
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/companies/show.blade.php
@extends('dashboard.index')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3>Company Information</h3>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <label class="form-label">Name:</label>
                        <p>{{ $company->name }}</p>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Email:</label>
                        <p>{{ $company->email }}</p>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Logo:</label>
                        <img src="{{ $company->logo_url }}" alt="Company Logo" class="img-fluid">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Website URL:</label>
                        <p>{{ $company->website_url }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3>Employees</h3>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        @foreach ($company->employees as $employee)
                        <li class="list-group-item">
                            {{ $employee->first_name }} {{ $employee->last_name }}
                            <br>
                            Email: {{ $employee->email }}
                            <br>
                            Phone Number: {{ $employee->phone_number }}
                            <br>
                            Intern: {{ $employee->is_intern ? 'Yes' : 'No' }}
                            <br>
                            Started At: {{ $employee->started_at }}
                        </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection