routes/web.php
<?php

use App\Http\Controllers\Dashboard\CompanyController;
use App\Http\Controllers\Dashboard\EmployeeController;
use App\Http\Controllers\ProfileController;
use App\Models\Employee;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Dashboard routes
Route::prefix('dashboard')->group(function () {

    // Dashboard homepage
    Route::get('/', function () {
        return view('dashboard.index');
    })->name('dashboard');

    // Dashboard category resource
    Route::resource('companies', CompanyController::class);

    // Dashboard tag resource
    Route::resource('employees', EmployeeController::class);
    Route::get('datatable-data', [CompanyController::class, 'getData'])->name('datatable.data');

})->middleware(['auth', 'verified']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Employee.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Employee extends Model
{
    use HasFactory;

    protected $fillable = [
        'company_id',
        'first_name',
        'last_name',
        'email',
        'phone_number',
        'is_intern',
        'started_at',
    ];

    protected $dates=[
        'started_at'
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function getInternshipDurationAttribute(): int
    {
        if ($this->is_intern && $this->started_at) {
            $startedAt = Carbon::parse($this->started_at);
            $now = Carbon::now();
            return $startedAt->diffInDays($now);
        }
        return 0;
    }
}

app/Http/Controllers/Dashboard/CompanyController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Company\CreateCompanyRequest;
use App\Http\Requests\Dashboard\Company\UpdateCompanyRequest;
use App\Mail\NewCompanyMail;
use App\Models\Company;
use App\Traits\UploadMedia;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class CompanyController extends Controller
{
    use UploadMedia;

    public function index(Request $request): View
    {
        $search = $request->input('search');
        $companiesQuery = Company::query();
        if ($search) {
            $companiesQuery->where('name', 'like', '%'.$search.'%')
                ->orWhere('email', 'like', '%'.$search.'%');
        }
        $companies = $companiesQuery->paginate(10);

        return view('dashboard.companies.index',
            ['companies' => $companies]
        );
    }

    public function create(): View
    {
        return view('dashboard.companies.create');
    }

    public function store(CreateCompanyRequest $request): RedirectResponse
    {
        $company = new company();
        $company->name = $request->validated('name');
        $company->email = $request->validated('email');
        $company->logo = $this->uploadImage('logo', 'company');
        $company->website_url = $request->validated('website_url');
        $company->save();
        Mail::to($company)->send(new NewCompanyMail($company));

        return redirect()->route('companies.index');
    }

    public function show(string $id): View
    {
        $company = Company::with('employees')->find($id);

        return view('dashboard.companies.show',
            ['company' => $company]
        );
    }

    public function edit(Company $company): View
    {
        return view('dashboard.companies.edit',
            ['company' => $company]
        );
    }

    public function update(UpdateCompanyRequest $request, Company $company): RedirectResponse
    {
        $company->name = $request->validated('name');
        $company->email = $request->validated('email');

        if ($request->hasfile('logo')) {
            $company->logo = $this->uploadImage('logo', 'company');
        }
        $company->website_url = $request->validated('website_url');
        $company->save();

        return redirect()->route('companies.index');
    }

    public function destroy(Company $company): RedirectResponse
    {
        $company->delete();

        return redirect()->route('companies.index');
    }
}

app/Http/Controllers/Dashboard/EmployeeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Employee\CreateEmployeeRequest;
use App\Http\Requests\Dashboard\Employee\UpdateEmployeeRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request): View
    {
        $search = $request->input('search');

        // Query to fetch employees
        $employeesQuery = Employee::query();

        // Apply search filter if search term is provided
        if ($search) {
            $employeesQuery->where('first_name', 'like', '%' . $search . '%')
                           ->orWhere('last_name', 'like', '%' . $search . '%')
                           ->orWhere('email', 'like', '%' . $search . '%');
        }
        $employees = $employeesQuery->paginate(10); // You can change the pagination limit as needed
        return view('dashboard.employees.index', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $companies = Company::all();

        return view('dashboard.employees.create', ['companies' => $companies]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateEmployeeRequest $request): RedirectResponse
    {
        $employee = new Employee();
        $employee->company_id = $request->validated('company_id');
        $employee->first_name = $request->validated('first_name');
        $employee->last_name = $request->validated('last_name');
        $employee->email = $request->validated('email');
        $employee->phone_number = $request->validated('phone_number');
        $employee->save();

        return redirect()->route('employees.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id): view
    {
        $employee = Employee::find($id);

        return view('dashboard.employees.show', ['employee' => $employee]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Employee $employee): view
    {
        $companies = Company::all();
        return view('dashboard.employees.edit',
            [
                'companies' => $companies,
                'employee' => $employee,
            ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee): RedirectResponse
    {
        $employee->company_id = $request->validated('company_id');
        $employee->first_name = $request->validated('first_name');
        $employee->last_name = $request->validated('last_name');
        $employee->email = $request->validated('email');
        $employee->phone_number = $request->validated('phone_number');
        $employee->save();

        return redirect()->route('employees.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id): RedirectResponse
    {
        $employee = Employee::find($id);
        $employee->delete();

        return redirect()->route('employees.index');
    }
}

resources/views/dashboard/employees/create.blade.php
@extends('dashboard.index')
@section('content')
    <div class="container px-5 mt-4">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="card">
            <div class="card-header d-flex">
                <h3 class="text-xl text-gray font-weight-bold">Add new Employee</h3>
            </div>
            <div class="card-body">
                <form action="{{route('employees.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>First name</label>
                        <input type="text" placeholder="first name" class="form-control" name="first_name">
                    </div>
                    <div class="form-group">
                        <label>Last name</label>
                        <input type="text" placeholder="last name" class="form-control" name="last_name">
                    </div>
                    <div class="form-group mt-2">
                        <label>Email</label>
                        <input type="email" placeholder="email" class="form-control " name="email">
                    </div>
                    <div class="form-group mt-2">
                        <label>Phone number</label>
                        <input type="text" placeholder="Phone number" class="form-control" name="phone_number">
                    </div>
                    <div class="form-group mt-2">
                        <label>Company</label>
                        <select class="form-control" id="company" name="company_id" >
                            <option value="">chooes company</option>
                            @foreach($companies as $company)
                            <option value="{{ $company->id }}">{{ $company->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group mt-2">
                        <input type="submit" value="Add Employee" class="btn btn-primary my-4 rounded">
                    </div>
                </form>
            </div>
        </div>
    </div>


    @endsection

resources/views/dashboard/employees/edit.blade.php
@extends('dashboard.index')
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Update current employee</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('employees.update', $employee->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>First Name</label>
                        <input type="text" placeholder="first name" class="form-control" name="first_name"
                            value="{{ $employee->first_name ? $employee->first_name : '' }}">
                    </div>
                    <div class="form-group">
                        <label>last name</label>
                        <input type="last_name" placeholder="last name" class="form-control" name="last_name"
                            value="{{ $employee->last_name ? $employee->last_name : '' }}">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" placeholder="Email Address" class="form-control" name="email"
                            value="{{ $employee->email ? $employee->email : '' }}">
                    </div>
                    <div class="form-group">
                        <label>Phone number</label>
                        <input type="text" placeholder="Phone" class="form-control" name="phone_number"
                            value="{{ $employee->phone_number ? $employee->phone_number : '' }}">
                    </div>
                    <div class="form-group mt-2">
                     <label>Company</label>
                     <select id="company" class="form-control" name="company_id">
                        @foreach ($companies as $company)
                            <option value="{{ $company->id }}" @selected($employee->company->id)>{{ $company->name }}</option>
                        @endforeach
                     </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update employee" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/employees/index.blade.php
@extends('dashboard.index')
@section('content')
    <div class="container px-5 mt-4">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h3 class="text-xl text-gray font-weight-bold">Employees Info</h3>
                <form action="{{ route('employees.index') }}" method="GET" class="form-inline">
                    <input type="text" name="search" class="form-control mr-2" placeholder="Search...">
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>
            <div class="card-body">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th> First Name</th>
                                    <th> Last Name</th>
                                    <th> Email</th>
                                    <th>Phone Number</th>
                                    <th>Company</th>
                                    <th class="text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($employees as $key => $employee)
                                    <tr style="vertical-align: center">
                                        <td>{{ $employee->id }}</td>
                                        <td>{{ $employee->first_name }}</td>
                                        <td>{{ $employee->last_name }}</td>
                                        <td>{{ $employee->email }}</td>
                                        <td>{{ $employee->phone_number }}</td>
                                        <td>{{ $employee->company->name }}</td>

                                        <td class="d-flex justify-content-end">
                                            <a href="{{ route('employees.edit', $employee->id) }}"> <button
                                                    class="btn btn-primary  rounded mr-1" style="width: 4.5rem">Edit</button>
                                            </a>
                                            <a href="{{ route('employees.show', $employee->id) }}"> <button
                                                    class="btn btn-info rounded px-2 mr-1"
                                                    style="width: 4.5rem">Show</button>
                                            </a>
                                            <form method="post" action="{{ route('employees.destroy', ['employee' => $employee->id]) }}" class="inline">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <button class="btn btn-danger rounded"style="width: 4.5rem">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $employees->links() }}
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/employees/show.blade.php
@extends('dashboard.index')
@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Employee Information</h1>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Company ID:</strong> {{ $employee->company_id }}</li>
                    <li class="list-group-item"><strong>First Name:</strong> {{ $employee->first_name }}</li>
                    <li class="list-group-item"><strong>Last Name:</strong> {{ $employee->last_name }}</li>
                    <li class="list-group-item"><strong>Email:</strong> {{ $employee->email }}</li>
                    <li class="list-group-item"><strong>Phone Number:</strong> {{ $employee->phone_number }}</li>
                    <li class="list-group-item"><strong>Is Intern:</strong> {{ $employee->is_intern ? 'Yes' : 'No' }}</li>
                    <li class="list-group-item"><strong>Started At:</strong> {{ $employee->started_at }}</li>
                </ul>
            </div>
        </div>
    </div>
@endsection